# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteArenaFelipePerius' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteArenaFelipePerius
  pod 'Alamofire', '~> 5.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'ObjectMapper', '~> 3.4'
  pod 'SDWebImage', '~> 5.0'

  target 'TesteArenaFelipePeriusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesteArenaFelipePeriusUITests' do
    # Pods for testing
  end

end
