//
//  ListRepositoriesConfigurator.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 08/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

/// Intercepts "prepare for segue" and delegates storyboard transition handling to the Router
extension ListRepositoriesViewController {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

/// Configurator composes the ListRepositories scene by connecting View, Interactor, and Presenter
/// and injecting their dependencies.
class ListRepositoriesConfigurator: NSObject {
  
    @IBOutlet weak var viewController: ListRepositoriesViewController!
    
    override func awakeFromNib() {
        let router = DefaultListRepositoriesRouter()
        router.viewController = viewController
        
        let presenter = DefaultListRepositoriesPresenter()
        presenter.viewController = viewController
        
        let interactor = DefaultListRepositoriesInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}