//
//  ListPullRequestsPresenter.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

/// Interface provided by a ListPullRequestsPresenter to receive inputs from a Interactor
protocol ListPullRequestsPresenter {

    /// function called to present an array of pull requests; `shouldAppend` adds the pull requests to the previously
    /// presented ones
    func presentPullRequests(_ pullRequests: [PullRequest], shouldAppend: Bool, hasMore: Bool)
    
    /// function called to present a request error
    func presentRequestError(_ error: Error)
}
