//
//  ListPullRequestsConfigurator.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

/// Configurator composes the ListPullRequests scene by connecting View, Interactor, and Presenter
/// and injecting their dependencies.
class ListPullRequestsConfigurator: NSObject {
  
    @IBOutlet weak var viewController: ListPullRequestsViewController!
    
    override func awakeFromNib() {
        let router = DefaultListPullRequestsRouter()
        router.viewController = viewController
        
        let presenter = DefaultListPullRequestsPresenter()
        presenter.viewController = viewController
        
        let interactor = DefaultListPullRequestsInteractor(repositoryService: GithubRepositoryService.shared)
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
