//
//  ListPullRequestsPresenterTests.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import desafio_ios
import XCTest

/*
class ListPullRequestsPresenterTests: XCTestCase {

    // MARK: - Subject under test
    
    var presenter: ListPullRequestsPresenter!

    // MARK: - Test doubles

    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        
        presenter = ListPullRequestsPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Tests
    
    func testSomething() {
        
    }
}
 */
