//
//  DefaultListRepositoriesRouter.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 08/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

/// This component handles the transitions and the data flow from ListRepositories scene to other scenes
class DefaultListRepositoriesRouter: ListRepositoriesRouter {
    
    weak var viewController: ListRepositoriesViewController!
    
    func showPullRequests() {
        guard viewController.selectedRepository != nil else {
            debugPrint("Error: trying to show the pull requests for a nil repository! Aborting.")
            return
        }
        let segueID = R.segue.listRepositoriesViewController.showPullRequests.identifier
        viewController.performSegue(withIdentifier: segueID, sender: nil)
    }
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == R.segue.listRepositoriesViewController.showPullRequests.identifier {
            let pullRequestsViewController = segue.destination as! ListPullRequestsViewController
            pullRequestsViewController.repository = viewController.selectedRepository
        }
    }
}
