//
//  DefaultListRepositoriesRouter.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 08/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

/// This component handles the transitions and the data flow from ListRepositories scene to other scenes
class DefaultListRepositoriesRouter: ListRepositoriesRouter {
    weak var viewController: ListRepositoriesViewController!
    
    // MARK: - Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        
    }
}
