//
//  ListRepositoriesViewController.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 08/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ListRepositoriesViewController: UIViewController, ListRepositoriesViewControllerInput {

    var interactor: ListRepositoriesInteractor!
    var router: ListRepositoriesRouter!
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // send request to interactor object
    }
    
    // MARK: - Display logic
    
    func displayViewModel(_ viewModel: ListRepositories.ViewModel) {
    
    }
    
    func updateViewModel(with repositories: [ListRepositories.ViewModel.Repository], shouldShowLoadMore: Bool) {
    
    }
}
