//
//  ListRepositoriesModels.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 08/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

struct ListRepositories {

	/// Describes the view state of ListRepositoriesViewController
	struct ViewModel {
        
        struct Repository {
            
        }
        
        var repositories: [Repository]
        var shouldShowLoadMore: Bool
        
		static var initialState: ViewModel {
            return ViewModel(repositories: [], shouldShowLoadMore: false)
        }
	}
}
