//
//  ListRepositoriesModels.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 08/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

struct ListRepositories {

	/// Describes the view state of ListRepositoriesViewController
	struct ViewModel {
        
        struct Repository {
            let name: String
            let description: String
            let forks: String
            let stars: String
            let owner: OwnerViewModel
        }
        
        var repositories: [Repository]
        var shouldShowLoadMore: Bool
        
		static var initialState: ViewModel {
            var repos = [Repository]()
            for i in 0..<30 {
                let owner = OwnerViewModel(profilePictureURL: nil, userName: "User\(i)", displayName: "John Doe \(i)")
                let repo = Repository(name: "Repo \(i)",
                                      description: "Description \(i)",
                                      forks: "\(arc4random() % 100000)",
                                      stars: "\(arc4random() % 100000)",
                                      owner: owner)
                repos.append(repo)
            }
            return ViewModel(repositories: repos, shouldShowLoadMore: true)
        }
	}
}
