project 'GitHub.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHub
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'
  pod 'PKHUD', '~> 4.0'

  target 'GitHubTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyJSON'
  end

end
