//
//  DefaultListPullRequestsInteractor.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

/// Implements the business logic behind the events that come from ListPullRequestsViewController
class DefaultListPullRequestsInteractor: ListPullRequestsInteractor {

    var presenter: ListPullRequestsPresenter!
    var repository: Repository!
    private(set) var pullRequests: [PullRequest] = []
    private let repositoryService: RepositoryService
    private var nextPage: UInt = 0
    
    init(repositoryService: RepositoryService) {
        self.repositoryService = repositoryService
    }
    
    // MARK: - Business logic
    
    func reloadPullRequests() {
        nextPage = 0
        requestNextPageOfPullRequests(shouldAppendResults: false)
    }
    
    private func requestNextPageOfPullRequests(shouldAppendResults: Bool) {
        repositoryService.pullRequests(
            for: repository,
            filterByState: nil,
            sortBy: nil,
            page: nextPage,
            onCompletion: { pullRequests, hasMorePages in
                self.nextPage += 1
                if shouldAppendResults {
                    self.pullRequests.append(contentsOf: pullRequests)
                } else {
                    self.pullRequests = pullRequests
                }
                self.presenter.presentPullRequests(pullRequests, shouldAppend: shouldAppendResults, hasMore: hasMorePages)
            }, onError: { error in
                self.presenter.presentRequestError(error)
            }
        )
    }
    
    func loadMorePullRequests() {
        guard nextPage > 0 else {
            debugPrint("Warning: trying to load more repos when `nextPage` is 0.")
            reloadPullRequests()
            return
        }
        
        requestNextPageOfPullRequests(shouldAppendResults: true)
    }
}
