//
//  DefaultListPullRequestsInteractor.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

/// Implements the business logic behind the events that come from ListPullRequestsViewController
class DefaultListPullRequestsInteractor: ListPullRequestsInteractor {

    var presenter: ListPullRequestsPresenter!
    
    var repository: Repository!
    
    // MARK: - Business logic
    
    func reloadPullRequests() {}
    
    func loadMorePullRequests() {}
}
