//
//  ListPullRequestsModels.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

struct ListPullRequests {

	/// Describes the view state of ListPullRequestsViewController
    struct ViewModel {
        
        struct PullRequest {
            let title: String
            let dateInfo: String
            let description: String
            let author: UserViewModel
        }
        
        var pullRequests: [PullRequest]
        var shouldShowLoadMore: Bool
        
        static var initialState: ViewModel {
            return ViewModel(pullRequests: [], shouldShowLoadMore: false)
        }
    }

}
