//
//  DefaultListPullRequestsRouter.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

/// This component handles the transitions and the data flow from ListPullRequests scene to other scenes
class DefaultListPullRequestsRouter: ListPullRequestsRouter {
    weak var viewController: ListPullRequestsViewController!
    
    // MARK: - Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        
    }
}
