//
//  DefaultListPullRequestsRouter.swift
//  desafio-ios
//
//  Created by Cicero Camargo on 09/04/17.
//  Copyright (c) 2017 Stationfy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

fileprivate typealias LocalizableString = R.string.defaultListPullRequestsRouter

/// This component handles the transitions and the data flow from ListPullRequests scene to other scenes
class DefaultListPullRequestsRouter: ListPullRequestsRouter {
    weak var viewController: ListPullRequestsViewController!
    
    // MARK: - Communication
    
    func showPullRequestDetail() {
        guard
            let pullRequest = viewController.selectedPullRequest,
            UIApplication.shared.canOpenURL(pullRequest.htmlURL)
        else {
            alertPullRequestDetailFailure()
            return
        }
        UIApplication.shared.openURL(pullRequest.htmlURL)
    }
    
    private func alertPullRequestDetailFailure() {
        viewController.presentDismissableAlert(
            title: LocalizableString.alertPullRequestDetailFailure_title(),
            message: LocalizableString.alertPullRequestDetailFailure_message(),
            dismissActionTitle: LocalizableString.alertPullRequestDetailFailure_dismiss()
        )
    }
}
